CREATE TABLE [WF].[ROLE_PROPERTIES_CELLS] (
    [ROLE_ID]           NVARCHAR (36)  NOT NULL,
    [PROPERTIES_ROW_ID] INT            NOT NULL,
    [PROPERTY_NAME]     NVARCHAR (64)  NOT NULL,
    [STRING_VALUE]      NVARCHAR (MAX) NULL,
	[TENANT_CODE]       NVARCHAR (36)  NULL DEFAULT 'D5561180-7617-4B67-B68B-1F0EA604B509',
    CONSTRAINT [PK_ROLE_PROPERTIES_CELLS] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [PROPERTIES_ROW_ID] ASC, [PROPERTY_NAME] ASC)
);


GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'租户编码',
    @level0type = N'SCHEMA',
    @level0name = N'WF',
    @level1type = N'TABLE',
    @level1name = N'ROLE_PROPERTIES_CELLS',
    @level2type = N'COLUMN',
    @level2name = N'TENANT_CODE'
GO

CREATE INDEX [IX_ROLE_PROPERTIES_CELLS_TENANT_CODE] ON [WF].[ROLE_PROPERTIES_CELLS] ([TENANT_CODE])
