CREATE TABLE [WF].[ROLE_PROPERTIES_ROWS] (
    [ROLE_ID]       NVARCHAR (36) NOT NULL,
    [ROW_NUMBER]    INT           NOT NULL,
	[TENANT_CODE]   NVARCHAR (36) NULL DEFAULT 'D5561180-7617-4B67-B68B-1F0EA604B509',
    [OPERATOR_TYPE] INT           CONSTRAINT [DF_ROLE_PROPERTIES_ROWS_OPERATOR_TYPE] DEFAULT ((2)) NULL,
    [OPERATOR]      NVARCHAR (64) NULL,
    CONSTRAINT [PK_ROLE_PROPERTIES_ROWS] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [ROW_NUMBER] ASC)
);


GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'租户编码',
    @level0type = N'SCHEMA',
    @level0name = N'WF',
    @level1type = N'TABLE',
    @level1name = N'ROLE_PROPERTIES_ROWS',
    @level2type = N'COLUMN',
    @level2name = N'TENANT_CODE'
GO

CREATE INDEX [IX_ROLE_PROPERTIES_ROWS_TENANT_CODE] ON [WF].[ROLE_PROPERTIES_ROWS] ([TENANT_CODE])
