CREATE TABLE [WF].[WORKFLOW_TASK_EXTERNALDATA] (
    [TASK_ID]    NVARCHAR (36) NOT NULL,
    [DATA_ID]    NVARCHAR (50) NOT NULL,
    [DATA_VALUE] NVARCHAR (50) NULL,
    [PROCESS_ID] NVARCHAR (36) NULL,
    CONSTRAINT [PK_WORKFLOW_TASK_EXTERNALDATA] PRIMARY KEY CLUSTERED ([TASK_ID] ASC, [DATA_ID] ASC)
);

