CREATE TABLE [WF].[WORKFLOW_TASK_RELATED_TASK] (
    [TASK_ID]       NVARCHAR (36) NOT NULL,
    [RALETIVE_ID]   NVARCHAR (36) NOT NULL,
    [RALETIVE_TYPE] INT           NULL,
    [LAG]           FLOAT (53)    NULL,
    [DAYTYPE]       INT           NULL,
    CONSTRAINT [PK_WORKFLOW_TASK_RELATED_TASK] PRIMARY KEY CLUSTERED ([TASK_ID] ASC, [RALETIVE_ID] ASC)
);

