CREATE TABLE [WF].[WORKFLOW_TASK_TEMPLATE_DETAIL] (
    [TASK_ID]         NVARCHAR (36)  NOT NULL,
    [TASK_NAME]       NVARCHAR (128) NOT NULL,
    [PARENT_ID]       NVARCHAR (36)  NOT NULL,
    [TIMESPAN]        FLOAT (53)     NULL,
    [KEY_POINT_LEVEL] INT            NULL,
    [SORT_ID]         INT            NULL,
    [TEMPLATE_KEY]    NVARCHAR (36)  NOT NULL,
    CONSTRAINT [PK_WORKFLOW_TASK_TEMPLATE_DETAIL_1] PRIMARY KEY CLUSTERED ([TASK_ID] ASC, [TEMPLATE_KEY] ASC)
);

