//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckCompileStatus.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckCompileStatus.Resource.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Starting....
        /// </summary>
        internal static string AnalyzingStartingInfo {
            get {
                return ResourceManager.GetString("AnalyzingStartingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011-12-07 Clark.  All rights reserved..
        /// </summary>
        internal static string AuthorInfo {
            get {
                return ResourceManager.GetString("AuthorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build FAILED.
        /// </summary>
        internal static string BuildFAILEDInfo {
            get {
                return ResourceManager.GetString("BuildFAILEDInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build succeeded.
        /// </summary>
        internal static string BuildsucceededInfo {
            get {
                return ResourceManager.GetString("BuildsucceededInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build succeeded, WARNING.
        /// </summary>
        internal static string BuildWARNINGInfo {
            get {
                return ResourceManager.GetString("BuildWARNINGInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCompileStatus [Version 1.0.0].
        /// </summary>
        internal static string CheckCompileStatusInfo {
            get {
                return ResourceManager.GetString("CheckCompileStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Starting....
        /// </summary>
        internal static string CompileStartingInfo {
            get {
                return ResourceManager.GetString("CompileStartingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Authenticating....
        /// </summary>
        internal static string GetCredentialsInfo {
            get {
                return ResourceManager.GetString("GetCredentialsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string GetLatestVersionProcessInfo {
            get {
                return ResourceManager.GetString("GetLatestVersionProcessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;, {0}.
        /// </summary>
        internal static string GetLatestVersionProcessInfo2 {
            get {
                return ResourceManager.GetString("GetLatestVersionProcessInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items get succeed!.
        /// </summary>
        internal static string ItemsGetSucceedInfo {
            get {
                return ResourceManager.GetString("ItemsGetSucceedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items ingored..
        /// </summary>
        internal static string ItemsIgnoredInfo {
            get {
                return ResourceManager.GetString("ItemsIgnoredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items to download..
        /// </summary>
        internal static string ItemsToDownloadInfo {
            get {
                return ResourceManager.GetString("ItemsToDownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Authenticated..
        /// </summary>
        internal static string NotifyCredentialsAuthenticatedInfo {
            get {
                return ResourceManager.GetString("NotifyCredentialsAuthenticatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the download....
        /// </summary>
        internal static string StartthedownloadInfo {
            get {
                return ResourceManager.GetString("StartthedownloadInfo", resourceCulture);
            }
        }
    }
}
