ALTER TABLE [dbo].[APP_OPERATION_TYPE]
    ADD CONSTRAINT [PK_APP_OPERATION_TYPE] PRIMARY KEY CLUSTERED ([GUID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

