ALTER TABLE [dbo].[LOG_USER_INFO]
    ADD CONSTRAINT [PK_LOG_USER_INFO] PRIMARY KEY CLUSTERED ([SORT] DESC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

