ALTER TABLE [dbo].[USER_OPEATION_LOG]
    ADD CONSTRAINT [PK_USER_OPEATION_LOG] PRIMARY KEY CLUSTERED ([ID] DESC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

