//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Applications.AccreditAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccreditResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccreditResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Applications.AccreditAdmin.Properties.AccreditResource", typeof(AccreditResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGU_ADMIN.
        /// </summary>
        internal static string AppCodeName {
            get {
                return ResourceManager.GetString("AppCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccreditAdmin.
        /// </summary>
        internal static string ConnAlias {
            get {
                return ResourceManager.GetString("ConnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_GROUPS.
        /// </summary>
        internal static string Func_CreateGroup {
            get {
                return ResourceManager.GetString("Func_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_ORGANIZATIONS.
        /// </summary>
        internal static string Func_CreateOrg {
            get {
                return ResourceManager.GetString("Func_CreateOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_USERS.
        /// </summary>
        internal static string Func_CreateUser {
            get {
                return ResourceManager.GetString("Func_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FURBISH_DELETE_GROUPS.
        /// </summary>
        internal static string Func_FurbishGroup {
            get {
                return ResourceManager.GetString("Func_FurbishGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FURBISH_DELETE_ORGANIZATIONS.
        /// </summary>
        internal static string Func_FurbishOrg {
            get {
                return ResourceManager.GetString("Func_FurbishOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FURBISH_DELETE_USERS.
        /// </summary>
        internal static string Func_FurbishUser {
            get {
                return ResourceManager.GetString("Func_FurbishUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP_ADD_USERS.
        /// </summary>
        internal static string Func_GroupAddUser {
            get {
                return ResourceManager.GetString("Func_GroupAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP_DEL_USERS.
        /// </summary>
        internal static string Func_GroupDelUser {
            get {
                return ResourceManager.GetString("Func_GroupDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT_USERS_PWD.
        /// </summary>
        internal static string Func_InitUserPwd {
            get {
                return ResourceManager.GetString("Func_InitUserPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIC_DELETE_GROUPS.
        /// </summary>
        internal static string Func_LogicDelGroup {
            get {
                return ResourceManager.GetString("Func_LogicDelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIC_DELETE_ORGANIZATIONS.
        /// </summary>
        internal static string Func_LogicDelOrg {
            get {
                return ResourceManager.GetString("Func_LogicDelOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIC_DELETE_USERS.
        /// </summary>
        internal static string Func_LogicDelUser {
            get {
                return ResourceManager.GetString("Func_LogicDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_GROUPS.
        /// </summary>
        internal static string Func_ModifyGroup {
            get {
                return ResourceManager.GetString("Func_ModifyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_ORGANIZATIONS.
        /// </summary>
        internal static string Func_ModifyOrg {
            get {
                return ResourceManager.GetString("Func_ModifyOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_USERS.
        /// </summary>
        internal static string Func_ModifyUser {
            get {
                return ResourceManager.GetString("Func_ModifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL_DELETE_GROUPS.
        /// </summary>
        internal static string Func_RealDelGroup {
            get {
                return ResourceManager.GetString("Func_RealDelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL_DELETE_ORGANIZATIONS.
        /// </summary>
        internal static string Func_RealDelOrg {
            get {
                return ResourceManager.GetString("Func_RealDelOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL_DELETE_USERS.
        /// </summary>
        internal static string Func_RealDelUser {
            get {
                return ResourceManager.GetString("Func_RealDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECRETARY_ADD.
        /// </summary>
        internal static string Func_SecretaryAdd {
            get {
                return ResourceManager.GetString("Func_SecretaryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECRETARY_DEL.
        /// </summary>
        internal static string Func_SecretaryDel {
            get {
                return ResourceManager.GetString("Func_SecretaryDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET_SIDELINE.
        /// </summary>
        internal static string Func_SetSideline {
            get {
                return ResourceManager.GetString("Func_SetSideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT_IN_GROUP.
        /// </summary>
        internal static string Func_SortInGroup {
            get {
                return ResourceManager.GetString("Func_SortInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT_IN_ORGANIZATIONS.
        /// </summary>
        internal static string Func_SortInOrg {
            get {
                return ResourceManager.GetString("Func_SortInOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000.
        /// </summary>
        internal static string OriginalSortDefault {
            get {
                return ResourceManager.GetString("OriginalSortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUPS.
        /// </summary>
        internal static string Table_Group {
            get {
                return ResourceManager.GetString("Table_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP_USERS.
        /// </summary>
        internal static string Table_GroupUser {
            get {
                return ResourceManager.GetString("Table_GroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZATIONS.
        /// </summary>
        internal static string Table_Org {
            get {
                return ResourceManager.GetString("Table_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU_USERS.
        /// </summary>
        internal static string Table_OuUser {
            get {
                return ResourceManager.GetString("Table_OuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWD_ARITHMETIC.
        /// </summary>
        internal static string Table_Pwd {
            get {
                return ResourceManager.GetString("Table_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANK_DEFINE.
        /// </summary>
        internal static string Table_RankDefine {
            get {
                return ResourceManager.GetString("Table_RankDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECRETARIES.
        /// </summary>
        internal static string Table_Secretary {
            get {
                return ResourceManager.GetString("Table_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS.
        /// </summary>
        internal static string Table_User {
            get {
                return ResourceManager.GetString("Table_User", resourceCulture);
            }
        }
    }
}
