//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.OA.Portal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.OA.DataObjects.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除权限表中的ResourceID不能为空.
        /// </summary>
        internal static string ACLDeleteByResourceIDIsNull {
            get {
                return ResourceManager.GetString("ACLDeleteByResourceIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限控制列表不能为空.
        /// </summary>
        internal static string ACLListIsNull {
            get {
                return ResourceManager.GetString("ACLListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取指定的用户修改详细信息.
        /// </summary>
        internal static string AppModifyDetailAdapter_FailToLoad {
            get {
                return ResourceManager.GetString("AppModifyDetailAdapter_FailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}数据无效,{1}.
        /// </summary>
        internal static string AppTraceReceiverUnValid {
            get {
                return ResourceManager.GetString("AppTraceReceiverUnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在授权系统中找到CodeName为&quot;{0}&quot;的应用.
        /// </summary>
        internal static string CanNotFoundApplicationCodeName {
            get {
                return ResourceManager.GetString("CanNotFoundApplicationCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在授权系统中找到CodeName为&quot;{0}&quot;的角色.
        /// </summary>
        internal static string CanNotFoundRoleCodeName {
            get {
                return ResourceManager.GetString("CanNotFoundRoleCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be of type {0}.
        /// </summary>
        internal static string CollectionValidateError {
            get {
                return ResourceManager.GetString("CollectionValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在配置文件中找到配置节{0}.
        /// </summary>
        internal static string ConfigSectionNotFound {
            get {
                return ResourceManager.GetString("ConfigSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在配置文件中找到元素集合{0}或集合中元素不符合要求.
        /// </summary>
        internal static string ConfigurationElementCollectionNotFound {
            get {
                return ResourceManager.GetString("ConfigurationElementCollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在配置文件中找到配置元素{0}.
        /// </summary>
        internal static string ConfigurationElementNotFound {
            get {
                return ResourceManager.GetString("ConfigurationElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要获得的配置元素的{0}为空.
        /// </summary>
        internal static string ConfigurationElementValueEmpty {
            get {
                return ResourceManager.GetString("ConfigurationElementValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}类反序列化不可用.
        /// </summary>
        internal static string DeserializeDisable {
            get {
                return ResourceManager.GetString("DeserializeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会签分发表的资源ID不能为空.
        /// </summary>
        internal static string DistributionID {
            get {
                return ResourceManager.GetString("DistributionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会签分发表的资源ID不能为空.
        /// </summary>
        internal static string DistributionIDIsNull {
            get {
                return ResourceManager.GetString("DistributionIDIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到文件{0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法访问{0}.
        /// </summary>
        internal static string IllegalPath {
            get {
                return ResourceManager.GetString("IllegalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WfOguRole的Key:{0}不合法，正确格式应为 appCode:roleCode.
        /// </summary>
        internal static string InvalidWfOguRoleID {
            get {
                return ResourceManager.GetString("InvalidWfOguRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载对象{0}失败，请确认该对象是否存在 的本地化字符串.
        /// </summary>
        internal static string LoadObjectError {
            get {
                return ResourceManager.GetString("LoadObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取文件流转过程中文件快照保留详细信息.
        /// </summary>
        internal static string ModifyDetailAdapter_FailToLoad {
            get {
                return ResourceManager.GetString("ModifyDetailAdapter_FailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对象{0}为空的本地化字符串.
        /// </summary>
        internal static string ObjectNullError {
            get {
                return ResourceManager.GetString("ObjectNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源文件夹与目标文件夹不能相同.
        /// </summary>
        internal static string SameRootPathName {
            get {
                return ResourceManager.GetString("SameRootPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法生成 HttpContext 的Xml文档.
        /// </summary>
        internal static string UserOperationLog_FailToGenerateHttpContextXml {
            get {
                return ResourceManager.GetString("UserOperationLog_FailToGenerateHttpContextXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取指定的操作日志.
        /// </summary>
        internal static string UserOperationLogAdapter_FailToGet {
            get {
                return ResourceManager.GetString("UserOperationLogAdapter_FailToGet", resourceCulture);
            }
        }
    }
}
