//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace CIIC.HSR.TSP.WF.Ctrl.Test.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TaskPluginSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DictionaryEntry[]))]
    public partial class TaskPlugin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTaskFromCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUserTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserTasksAccomplishedOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserAccomplishedTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncProcessOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TaskPlugin() {
            this.Url = global::CIIC.HSR.TSP.WF.Ctrl.Test.Properties.Settings.Default.CIIC_HSR_TSP_WF_Ctrl_Test_localhost_TaskPlugin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryTaskCompletedEventHandler QueryTaskCompleted;
        
        /// <remarks/>
        public event GetTaskFromCacheCompletedEventHandler GetTaskFromCacheCompleted;
        
        /// <remarks/>
        public event SendUserTasksCompletedEventHandler SendUserTasksCompleted;
        
        /// <remarks/>
        public event SetUserTasksAccomplishedCompletedEventHandler SetUserTasksAccomplishedCompleted;
        
        /// <remarks/>
        public event DeleteUserAccomplishedTasksCompletedEventHandler DeleteUserAccomplishedTasksCompleted;
        
        /// <remarks/>
        public event DeleteUserTasksCompletedEventHandler DeleteUserTasksCompleted;
        
        /// <remarks/>
        public event SyncProcessCompletedEventHandler SyncProcessCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagedCollectionOfUSER_TASKBO_PROCESS QueryTask(string tenantCode, string userId, UserTaskQueryCondition condition, int pageIndex, int pageSize, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> totalCount) {
            object[] results = this.Invoke("QueryTask", new object[] {
                        tenantCode,
                        userId,
                        condition,
                        pageIndex,
                        pageSize,
                        totalCount});
            return ((PagedCollectionOfUSER_TASKBO_PROCESS)(results[0]));
        }
        
        /// <remarks/>
        public void QueryTaskAsync(string tenantCode, string userId, UserTaskQueryCondition condition, int pageIndex, int pageSize, System.Nullable<int> totalCount) {
            this.QueryTaskAsync(tenantCode, userId, condition, pageIndex, pageSize, totalCount, null);
        }
        
        /// <remarks/>
        public void QueryTaskAsync(string tenantCode, string userId, UserTaskQueryCondition condition, int pageIndex, int pageSize, System.Nullable<int> totalCount, object userState) {
            if ((this.QueryTaskOperationCompleted == null)) {
                this.QueryTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryTaskOperationCompleted);
            }
            this.InvokeAsync("QueryTask", new object[] {
                        tenantCode,
                        userId,
                        condition,
                        pageIndex,
                        pageSize,
                        totalCount}, this.QueryTaskOperationCompleted, userState);
        }
        
        private void OnQueryTaskOperationCompleted(object arg) {
            if ((this.QueryTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryTaskCompleted(this, new QueryTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTaskFromCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagedCollectionOfUSER_TASKBO_PROCESS GetTaskFromCache(string cacheKey, string userId, string tenantCode) {
            object[] results = this.Invoke("GetTaskFromCache", new object[] {
                        cacheKey,
                        userId,
                        tenantCode});
            return ((PagedCollectionOfUSER_TASKBO_PROCESS)(results[0]));
        }
        
        /// <remarks/>
        public void GetTaskFromCacheAsync(string cacheKey, string userId, string tenantCode) {
            this.GetTaskFromCacheAsync(cacheKey, userId, tenantCode, null);
        }
        
        /// <remarks/>
        public void GetTaskFromCacheAsync(string cacheKey, string userId, string tenantCode, object userState) {
            if ((this.GetTaskFromCacheOperationCompleted == null)) {
                this.GetTaskFromCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaskFromCacheOperationCompleted);
            }
            this.InvokeAsync("GetTaskFromCache", new object[] {
                        cacheKey,
                        userId,
                        tenantCode}, this.GetTaskFromCacheOperationCompleted, userState);
        }
        
        private void OnGetTaskFromCacheOperationCompleted(object arg) {
            if ((this.GetTaskFromCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaskFromCacheCompleted(this, new GetTaskFromCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUserTasks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendUserTasks(string josn, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DictionaryEntry[] args) {
            this.Invoke("SendUserTasks", new object[] {
                        josn,
                        args});
        }
        
        /// <remarks/>
        public void SendUserTasksAsync(string josn, DictionaryEntry[] args) {
            this.SendUserTasksAsync(josn, args, null);
        }
        
        /// <remarks/>
        public void SendUserTasksAsync(string josn, DictionaryEntry[] args, object userState) {
            if ((this.SendUserTasksOperationCompleted == null)) {
                this.SendUserTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUserTasksOperationCompleted);
            }
            this.InvokeAsync("SendUserTasks", new object[] {
                        josn,
                        args}, this.SendUserTasksOperationCompleted, userState);
        }
        
        private void OnSendUserTasksOperationCompleted(object arg) {
            if ((this.SendUserTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUserTasksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserTasksAccomplished", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetUserTasksAccomplished(string josn, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DictionaryEntry[] args) {
            this.Invoke("SetUserTasksAccomplished", new object[] {
                        josn,
                        args});
        }
        
        /// <remarks/>
        public void SetUserTasksAccomplishedAsync(string josn, DictionaryEntry[] args) {
            this.SetUserTasksAccomplishedAsync(josn, args, null);
        }
        
        /// <remarks/>
        public void SetUserTasksAccomplishedAsync(string josn, DictionaryEntry[] args, object userState) {
            if ((this.SetUserTasksAccomplishedOperationCompleted == null)) {
                this.SetUserTasksAccomplishedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserTasksAccomplishedOperationCompleted);
            }
            this.InvokeAsync("SetUserTasksAccomplished", new object[] {
                        josn,
                        args}, this.SetUserTasksAccomplishedOperationCompleted, userState);
        }
        
        private void OnSetUserTasksAccomplishedOperationCompleted(object arg) {
            if ((this.SetUserTasksAccomplishedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserTasksAccomplishedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserAccomplishedTasks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUserAccomplishedTasks(string josn, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DictionaryEntry[] args) {
            this.Invoke("DeleteUserAccomplishedTasks", new object[] {
                        josn,
                        args});
        }
        
        /// <remarks/>
        public void DeleteUserAccomplishedTasksAsync(string josn, DictionaryEntry[] args) {
            this.DeleteUserAccomplishedTasksAsync(josn, args, null);
        }
        
        /// <remarks/>
        public void DeleteUserAccomplishedTasksAsync(string josn, DictionaryEntry[] args, object userState) {
            if ((this.DeleteUserAccomplishedTasksOperationCompleted == null)) {
                this.DeleteUserAccomplishedTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserAccomplishedTasksOperationCompleted);
            }
            this.InvokeAsync("DeleteUserAccomplishedTasks", new object[] {
                        josn,
                        args}, this.DeleteUserAccomplishedTasksOperationCompleted, userState);
        }
        
        private void OnDeleteUserAccomplishedTasksOperationCompleted(object arg) {
            if ((this.DeleteUserAccomplishedTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserAccomplishedTasksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUserTasks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUserTasks(string josn, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] DictionaryEntry[] args) {
            this.Invoke("DeleteUserTasks", new object[] {
                        josn,
                        args});
        }
        
        /// <remarks/>
        public void DeleteUserTasksAsync(string josn, DictionaryEntry[] args) {
            this.DeleteUserTasksAsync(josn, args, null);
        }
        
        /// <remarks/>
        public void DeleteUserTasksAsync(string josn, DictionaryEntry[] args, object userState) {
            if ((this.DeleteUserTasksOperationCompleted == null)) {
                this.DeleteUserTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserTasksOperationCompleted);
            }
            this.InvokeAsync("DeleteUserTasks", new object[] {
                        josn,
                        args}, this.DeleteUserTasksOperationCompleted, userState);
        }
        
        private void OnDeleteUserTasksOperationCompleted(object arg) {
            if ((this.DeleteUserTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserTasksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SyncProcess", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncProcess(string json) {
            this.Invoke("SyncProcess", new object[] {
                        json});
        }
        
        /// <remarks/>
        public void SyncProcessAsync(string json) {
            this.SyncProcessAsync(json, null);
        }
        
        /// <remarks/>
        public void SyncProcessAsync(string json, object userState) {
            if ((this.SyncProcessOperationCompleted == null)) {
                this.SyncProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncProcessOperationCompleted);
            }
            this.InvokeAsync("SyncProcess", new object[] {
                        json}, this.SyncProcessOperationCompleted, userState);
        }
        
        private void OnSyncProcessOperationCompleted(object arg) {
            if ((this.SyncProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncProcessCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserTaskQueryCondition {
        
        private TaskStatus taskTypeField;
        
        private WfProcessStatus processStatusField;
        
        private string taskTitleField;
        
        private string departmentCodeField;
        
        private string applicationNameField;
        
        private string programNameField;
        
        private System.Nullable<System.DateTime> createdFromField;
        
        private System.Nullable<System.DateTime> createdToField;
        
        private string creatorUserIdField;
        
        /// <remarks/>
        public TaskStatus TaskType {
            get {
                return this.taskTypeField;
            }
            set {
                this.taskTypeField = value;
            }
        }
        
        /// <remarks/>
        public WfProcessStatus ProcessStatus {
            get {
                return this.processStatusField;
            }
            set {
                this.processStatusField = value;
            }
        }
        
        /// <remarks/>
        public string TaskTitle {
            get {
                return this.taskTitleField;
            }
            set {
                this.taskTitleField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedFrom {
            get {
                return this.createdFromField;
            }
            set {
                this.createdFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedTo {
            get {
                return this.createdToField;
            }
            set {
                this.createdToField = value;
            }
        }
        
        /// <remarks/>
        public string CreatorUserId {
            get {
                return this.creatorUserIdField;
            }
            set {
                this.creatorUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TaskStatus {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Unprocessed,
        
        /// <remarks/>
        Processed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum WfProcessStatus {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        NotRunning,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Completed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DictionaryEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class USER_TASKBO_PROCESS {
        
        private string tASK_GUIDField;
        
        private string aPPLICATION_NAMEField;
        
        private string pROGRAM_NAMEField;
        
        private System.Nullable<int> tASK_LEVELField;
        
        private string tASK_TITLEField;
        
        private string rESOURCE_IDField;
        
        private string pROCESS_IDField;
        
        private string aCTIVITY_IDField;
        
        private string uRLField;
        
        private string dATAField;
        
        private System.Nullable<int> eMERGENCYField;
        
        private string pURPOSEField;
        
        private string sTATUSField;
        
        private System.Nullable<System.DateTime> tASK_START_TIMEField;
        
        private System.Nullable<System.DateTime> eXPIRE_TIMEField;
        
        private string sOURCE_IDField;
        
        private string sOURCE_NAMEField;
        
        private string sEND_TO_USERField;
        
        private string sEND_TO_USER_NAMEField;
        
        private System.Nullable<System.DateTime> rEAD_TIMEField;
        
        private string cATEGORY_GUIDField;
        
        private System.Nullable<int> tOP_FLAGField;
        
        private string dRAFT_DEPARTMENT_NAMEField;
        
        private System.Nullable<System.DateTime> dELIVER_TIMEField;
        
        private string dRAFT_USER_IDField;
        
        private string dRAFT_USER_NAMEField;
        
        private string tenantCodeField;
        
        private string taskTypeField;
        
        private string departmentCodeField;
        
        private string departmentNameField;
        
        private string pROCESS_KEYField;
        
        private string pROCESS_NAMEField;
        
        private string pROCESS_STATUSField;
        
        private System.DateTime createdField;
        
        /// <remarks/>
        public string TASK_GUID {
            get {
                return this.tASK_GUIDField;
            }
            set {
                this.tASK_GUIDField = value;
            }
        }
        
        /// <remarks/>
        public string APPLICATION_NAME {
            get {
                return this.aPPLICATION_NAMEField;
            }
            set {
                this.aPPLICATION_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PROGRAM_NAME {
            get {
                return this.pROGRAM_NAMEField;
            }
            set {
                this.pROGRAM_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TASK_LEVEL {
            get {
                return this.tASK_LEVELField;
            }
            set {
                this.tASK_LEVELField = value;
            }
        }
        
        /// <remarks/>
        public string TASK_TITLE {
            get {
                return this.tASK_TITLEField;
            }
            set {
                this.tASK_TITLEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_ID {
            get {
                return this.rESOURCE_IDField;
            }
            set {
                this.rESOURCE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_ID {
            get {
                return this.pROCESS_IDField;
            }
            set {
                this.pROCESS_IDField = value;
            }
        }
        
        /// <remarks/>
        public string ACTIVITY_ID {
            get {
                return this.aCTIVITY_IDField;
            }
            set {
                this.aCTIVITY_IDField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public string DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EMERGENCY {
            get {
                return this.eMERGENCYField;
            }
            set {
                this.eMERGENCYField = value;
            }
        }
        
        /// <remarks/>
        public string PURPOSE {
            get {
                return this.pURPOSEField;
            }
            set {
                this.pURPOSEField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TASK_START_TIME {
            get {
                return this.tASK_START_TIMEField;
            }
            set {
                this.tASK_START_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EXPIRE_TIME {
            get {
                return this.eXPIRE_TIMEField;
            }
            set {
                this.eXPIRE_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_ID {
            get {
                return this.sOURCE_IDField;
            }
            set {
                this.sOURCE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_NAME {
            get {
                return this.sOURCE_NAMEField;
            }
            set {
                this.sOURCE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SEND_TO_USER {
            get {
                return this.sEND_TO_USERField;
            }
            set {
                this.sEND_TO_USERField = value;
            }
        }
        
        /// <remarks/>
        public string SEND_TO_USER_NAME {
            get {
                return this.sEND_TO_USER_NAMEField;
            }
            set {
                this.sEND_TO_USER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> READ_TIME {
            get {
                return this.rEAD_TIMEField;
            }
            set {
                this.rEAD_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string CATEGORY_GUID {
            get {
                return this.cATEGORY_GUIDField;
            }
            set {
                this.cATEGORY_GUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TOP_FLAG {
            get {
                return this.tOP_FLAGField;
            }
            set {
                this.tOP_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string DRAFT_DEPARTMENT_NAME {
            get {
                return this.dRAFT_DEPARTMENT_NAMEField;
            }
            set {
                this.dRAFT_DEPARTMENT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DELIVER_TIME {
            get {
                return this.dELIVER_TIMEField;
            }
            set {
                this.dELIVER_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string DRAFT_USER_ID {
            get {
                return this.dRAFT_USER_IDField;
            }
            set {
                this.dRAFT_USER_IDField = value;
            }
        }
        
        /// <remarks/>
        public string DRAFT_USER_NAME {
            get {
                return this.dRAFT_USER_NAMEField;
            }
            set {
                this.dRAFT_USER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string TenantCode {
            get {
                return this.tenantCodeField;
            }
            set {
                this.tenantCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TaskType {
            get {
                return this.taskTypeField;
            }
            set {
                this.taskTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_KEY {
            get {
                return this.pROCESS_KEYField;
            }
            set {
                this.pROCESS_KEYField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_NAME {
            get {
                return this.pROCESS_NAMEField;
            }
            set {
                this.pROCESS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PROCESS_STATUS {
            get {
                return this.pROCESS_STATUSField;
            }
            set {
                this.pROCESS_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PagedCollectionOfUSER_TASKBO_PROCESS {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        private int totalItemsField;
        
        private USER_TASKBO_PROCESS[] itemsField;
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int TotalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
            }
        }
        
        /// <remarks/>
        public USER_TASKBO_PROCESS[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void QueryTaskCompletedEventHandler(object sender, QueryTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagedCollectionOfUSER_TASKBO_PROCESS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagedCollectionOfUSER_TASKBO_PROCESS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTaskFromCacheCompletedEventHandler(object sender, GetTaskFromCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaskFromCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTaskFromCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagedCollectionOfUSER_TASKBO_PROCESS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagedCollectionOfUSER_TASKBO_PROCESS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendUserTasksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetUserTasksAccomplishedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteUserAccomplishedTasksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteUserTasksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SyncProcessCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591