//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Library.Passport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Library.Passport.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绝对时间超时.
        /// </summary>
        internal static string AbsoluteTimeExpired {
            get {
                return ResourceManager.GetString("AbsoluteTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能根据登录名&quot;{0}&quot;找到用户.
        /// </summary>
        internal static string CanNotFindUser {
            get {
                return ResourceManager.GetString("CanNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能从当前线程或HttpContext中取得用户的登录和权限信息(Principal).
        /// </summary>
        internal static string CanNotGetPrincipal {
            get {
                return ResourceManager.GetString("CanNotGetPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法从url或cookie中得到有效的ticket.
        /// </summary>
        internal static string CanNotGetTicket {
            get {
                return ResourceManager.GetString("CanNotGetTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function initControlsFocus(signInNameID, oldPasswordID) {
        ///	var signInName = document.all(signInNameID);
        ///	var oldPassword = document.all(oldPasswordID);
        ///
        ///	try {
        ///		document.onkeydown = null;
        ///
        ///		if (signInName) {
        ///			if (signInName.value.length &gt; 0) {
        ///				if (oldPassword)
        ///					oldPassword.focus();
        ///				else
        ///					signInName.focus();
        ///			}
        ///			else
        ///				signInName.focus();
        ///		}
        ///	}
        ///	catch (e) {
        ///	}
        ///}
        ///
        ///function doDetailErrorMessageClick(detailErrorMessageID) {
        ///	var detailErrorMessage = document.all [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changePasswordScript {
            get {
                return ResourceManager.GetString("changePasswordScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 认证服务器不匹配.
        /// </summary>
        internal static string DifferentAthenticateServer {
            get {
                return ResourceManager.GetString("DifferentAthenticateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前Windows帐号的域名是&quot;{0}&quot;，应该是&quot;{1}.
        /// </summary>
        internal static string DomainNameMismatch {
            get {
                return ResourceManager.GetString("DomainNameMismatch", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fail {
            get {
                object obj = ResourceManager.GetObject("fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在角色判断时，提供的应用、角色字符串格式不正确。正确的格式应该为(应用的名称1:角色名称11,角色名称12,...;应用名称2:角色名称21,角色名称22,...).
        /// </summary>
        internal static string InvalidAppRoleNameDescription {
            get {
                return ResourceManager.GetString("InvalidAppRoleNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP不正确.
        /// </summary>
        internal static string IPInvalid {
            get {
                return ResourceManager.GetString("IPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能得到当前访问页面的用户ID，请检查IIS设置中，该页面是否禁止匿名访问.
        /// </summary>
        internal static string PageMustForbidAnonymousAccess {
            get {
                return ResourceManager.GetString("PageMustForbidAnonymousAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数&quot;{0}&quot;是认证服务的保留字，请不要在url中包含&quot;{0}&quot;参数.
        /// </summary>
        internal static string ParamIsReserved {
            get {
                return ResourceManager.GetString("ParamIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; language=&quot;javascript&quot;&gt;
        ///	function initControlsFocus(signInNameID, passwordID)
        ///	{
        ///		var signInName = document.all(signInNameID);
        ///		var password = document.all(passwordID);
        ///
        ///		try
        ///		{
        ///			document.onkeydown = null;
        ///
        ///			if (signInName)
        ///			{
        ///				if (signInName.value.length &gt; 0)
        ///					if (password)
        ///						password.focus();
        ///					else
        ///						signInName.focus();
        ///				else
        ///					signInName.focus();
        ///			}
        ///		}
        ///		catch(e)
        ///		{
        ///		}
        ///	}
        ///
        ///	function doDetailErrorMessageClick(d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signInControlScript {
            get {
                return ResourceManager.GetString("signInControlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string SignInInfoExtraProperties {
            get {
                return ResourceManager.GetString("SignInInfoExtraProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相对时间超时.
        /// </summary>
        internal static string SlidingTimeExpired {
            get {
                return ResourceManager.GetString("SlidingTimeExpired", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap success {
            get {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户&quot;{0}&quot;的ticket失效，原因为{1}.
        /// </summary>
        internal static string TicketInvalidReason {
            get {
                return ResourceManager.GetString("TicketInvalidReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户&apos;{0}&apos;认证失败，请检查用户名和密码是否正确。.
        /// </summary>
        internal static string UserAuthenticateFail {
            get {
                return ResourceManager.GetString("UserAuthenticateFail", resourceCulture);
            }
        }
    }
}
