SELECT D.PROCESS_KEY, D.APPLICATION_NAME, D.PROGRAM_NAME, D.PROCESS_NAME, D.ENABLED, D.CREATE_TIME, D.CREATOR_ID,   
	D.CREATOR_NAME, D.MODIFY_TIME, D.MODIFIER_ID, D.MODIFIER_NAME, D.IMPORT_TIME, D.IMPORT_USER_ID, D.IMPORT_USER_NAME
FROM WF.PROCESS_DESCRIPTORS D
WHERE EXISTS(SELECT USER_ID, USER_NAME
	FROM WF.MATRIX_MAIN MM INNER JOIN WF.MATRIX_ROWS_USERS MRU ON MM.MATRIX_ID = MRU.MATRIX_ID
	WHERE USER_ID = {0} AND D.PROCESS_KEY = MM.PROCESS_KEY AND D.TENANT_CODE = MM.TENANT_CODE)