SELECT D.PROCESS_KEY, D.APPLICATION_NAME, D.PROGRAM_NAME, D.PROCESS_NAME, D.ENABLED, D.CREATE_TIME, D.CREATOR_ID,   
	D.CREATOR_NAME, D.MODIFY_TIME, D.MODIFIER_ID, D.MODIFIER_NAME, D.IMPORT_TIME, D.IMPORT_USER_ID, D.IMPORT_USER_NAME
FROM WF.PROCESS_DESCRIPTOR_DIMENSIONS DIM INNER JOIN WF.PROCESS_DESCRIPTORS D ON DIM.PROCESS_KEY = D.PROCESS_KEY
WHERE DIM.Data.exist('Process/descendant::Resource[@ID=''{0}'']') > 0