SELECT P.INSTANCE_ID, P.RESOURCE_ID, P.APPLICATION_NAME, P.PROGRAM_NAME, P.PROCESS_NAME, P.DESCRIPTOR_KEY, P.CREATOR_ID,
	P.CREATOR_NAME, P.DEPARTMENT_ID, P.DEPARTMENT_NAME, P.START_TIME, P.STATUS, P.COMMITTED,
	CAST('' AS NVARCHAR(255)) AS TASK_TITLE, 0 AS IS_TASK, CAST('' AS NVARCHAR(36)) AS LASTEST_TASK_ID
FROM WF.PROCESS_INSTANCES P
WHERE P.COMMITTED = 1 AND P.STATUS <> 'Completed' AND P.STATUS <> 'Aborted' AND
EXISTS(SELECT * FROM WF.PROCESS_CURRENT_ASSIGNEES A WHERE A.USER_ID = {0} AND A.PROCESS_ID = P.INSTANCE_ID)
ORDER BY P.CREATE_TIME DESC