CREATE PROCEDURE [WF].[ImportInvalidAssignees]

AS
BEGIN
    TRUNCATE TABLE WF.INVALID_ASSIGNEES;

    INSERT INTO WF.INVALID_ASSIGNEES
           (PROCESS_ID, ACTIVITY_ID, USER_ID, USER_NAME, USER_PATH, ACTIVITY_START_TIME, ACTIVITY_STATUS)
		SELECT P.INSTANCE_ID AS PROCESS_ID, A.ACTIVITY_ID, CA.USER_ID, CA.USER_NAME, CA.USER_PATH, A.START_TIME AS ACTIVITY_START_TIME, A.STATUS AS ACTIVITY_STATUS
		FROM WF.PROCESS_INSTANCES AS P INNER JOIN
			WF.PROCESS_CURRENT_ACTIVITIES AS A ON P.INSTANCE_ID = A.PROCESS_ID INNER JOIN
			WF.PROCESS_CURRENT_ASSIGNEES AS CA ON A.ACTIVITY_ID = CA.ACTIVITY_ID
		WHERE (A.STATUS = N'Pending' OR
				A.STATUS = N'NotRunning' OR
				A.STATUS = N'Running') AND (CA.USER_ID NOT IN
					(SELECT ACTIVE_USER_ID
					FROM WF.ACTIVE_USERS))
END


