CREATE PROCEDURE [dbo].[GET_INHERITED_SON_APPLICATIONS]
@APP_ID NVARCHAR(36),
@INHERITED_STATE INT
AS
DECLARE @ROOT_LEVEL NVARCHAR(32)
SELECT @ROOT_LEVEL=RESOURCE_LEVEL FROM APPLICATIONS WHERE ID = @APP_ID
SELECT *
FROM APPLICATIONS
WHERE RESOURCE_LEVEL LIKE @ROOT_LEVEL+'%'
AND INHERITED_STATE & @INHERITED_STATE = @INHERITED_STATE
AND LEN(RESOURCE_LEVEL) = LEN(@ROOT_LEVEL) + 3
		
ORDER BY RESOURCE_LEVEL
