CREATE PROCEDURE [dbo].[GET_INHERITED_APPLICATIONS]
@APP_ID NVARCHAR(36),
@INHERITED_STATE INT
AS
DECLARE @ROOT_LEVEL NVARCHAR(32)
SELECT @ROOT_LEVEL=RESOURCE_LEVEL FROM APPLICATIONS WHERE ID = @APP_ID
SELECT * INTO #APP_TEMP
FROM APPLICATIONS
WHERE (RESOURCE_LEVEL LIKE @ROOT_LEVEL+'%'
		AND INHERITED_STATE & @INHERITED_STATE = @INHERITED_STATE)
OR ID = @APP_ID
ORDER BY RESOURCE_LEVEL
_loop:
	DELETE FROM #APP_TEMP
	WHERE LEFT(RESOURCE_LEVEL, LEN(RESOURCE_LEVEL)-3) NOT IN (SELECT RESOURCE_LEVEL FROM #APP_TEMP)
	AND RESOURCE_LEVEL <> @ROOT_LEVEL
IF (@@ROWCOUNT > 0) GOTO _loop
SELECT * FROM #APP_TEMP
WHERE ID <> @APP_ID
