//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Web.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeluxeWebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeluxeWebResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Web.Library.Resources.DeluxeWebResource", typeof(DeluxeWebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating design-time HTML:\n\n.
        /// </summary>
        internal static string DesignerTimeErrorMessage {
            get {
                return ResourceManager.GetString("DesignerTimeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能从类别{0}转换到类别{1}.
        /// </summary>
        internal static string E_CanNotConvertTypeTo {
            get {
                return ResourceManager.GetString("E_CanNotConvertTypeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScriptConverter注册时冲突：{0}和{1}不能同时都支持对{2}的序列化！.
        /// </summary>
        internal static string E_ConverterConflict {
            get {
                return ResourceManager.GetString("E_ConverterConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经存在此Url：{0}.
        /// </summary>
        internal static string E_HasExistUrl {
            get {
                return ResourceManager.GetString("E_HasExistUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行此操作时，当前的执行的HttpHandler必须是Page类实例.
        /// </summary>
        internal static string E_HttpHandlerMustBePageClass {
            get {
                return ResourceManager.GetString("E_HttpHandlerMustBePageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}是非法的文档图标路径格式.
        /// </summary>
        internal static string E_InvalidContentLogoImagePath {
            get {
                return ResourceManager.GetString("E_InvalidContentLogoImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用级别太深大于{0}级.
        /// </summary>
        internal static string E_InvokeLevelTooDeep {
            get {
                return ResourceManager.GetString("E_InvokeLevelTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不是{1}的子类或实现类.
        /// </summary>
        internal static string E_NoInheritFrom {
            get {
                return ResourceManager.GetString("E_NoInheritFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ScriptManager is required on the page to use ASP.NET AJAX Script Components..
        /// </summary>
        internal static string E_NoScriptManager {
            get {
                return ResourceManager.GetString("E_NoScriptManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的基类不是Control.
        /// </summary>
        internal static string E_NotControl {
            get {
                return ResourceManager.GetString("E_NotControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的基类不是JavaScriptConverter.
        /// </summary>
        internal static string E_NotJavaScriptConverter {
            get {
                return ResourceManager.GetString("E_NotJavaScriptConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class does not allow setting of ScriptPath..
        /// </summary>
        internal static string E_SciptPathNotAllowed {
            get {
                return ResourceManager.GetString("E_SciptPathNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeKey{0}已经存在.
        /// </summary>
        internal static string E_TypeKeyExist {
            get {
                return ResourceManager.GetString("E_TypeKeyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的类{0}.
        /// </summary>
        internal static string E_UnknownType {
            get {
                return ResourceManager.GetString("E_UnknownType", resourceCulture);
            }
        }
    }
}
