//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Web.Library.Script.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AtlasWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AtlasWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Web.Library.Script.Properties.AtlasWeb", typeof(AtlasWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of items has already been deserialized into a single dictionary by the JavaScriptSerializer. To change the maximum allowed JSON dictionary entry count from its current value of {0}, change the &quot;aspnet:MaxJsonDeserializerMembers&quot; setting. See http://go.microsoft.com/fwlink/?LinkId=238386 for more information..
        /// </summary>
        internal static string CollectionCountExceeded_JavaScriptObjectDeserializer {
            get {
                return ResourceManager.GetString("CollectionCountExceeded_JavaScriptObjectDeserializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported for deserialization of an array..
        /// </summary>
        internal static string JSON_ArrayTypeNotSupported {
            get {
                return ResourceManager.GetString("JSON_ArrayTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON_BadEscape=Unrecognized escape sequence..
        /// </summary>
        internal static string JSON_BadEscape {
            get {
                return ResourceManager.GetString("JSON_BadEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert object of type &apos;{0}&apos; to type &apos;{1}&apos;.
        /// </summary>
        internal static string JSON_CannotConvertObjectToType {
            get {
                return ResourceManager.GetString("JSON_CannotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create instance of {0}..
        /// </summary>
        internal static string JSON_CannotCreateListType {
            get {
                return ResourceManager.GetString("JSON_CannotCreateListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize member &apos;{0}&apos; on type &apos;{1}&apos;..
        /// </summary>
        internal static string JSON_CannotSerializeMemberGeneric {
            get {
                return ResourceManager.GetString("JSON_CannotSerializeMemberGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular reference was detected while serializing an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string JSON_CircularReference {
            get {
                return ResourceManager.GetString("JSON_CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecursionLimit exceeded..
        /// </summary>
        internal static string JSON_DepthLimitExceeded {
            get {
                return ResourceManager.GetString("JSON_DepthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize object graph into type of &apos;{0}&apos;..
        /// </summary>
        internal static string JSON_DeserializerTypeMismatch {
            get {
                return ResourceManager.GetString("JSON_DeserializerTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not supported for serialization/deserialization of a dictionary, keys must be strings or objects..
        /// </summary>
        internal static string JSON_DictionaryTypeNotSupported {
            get {
                return ResourceManager.GetString("JSON_DictionaryTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object passed in, &apos;{&apos; expected..
        /// </summary>
        internal static string JSON_ExpectedOpenBrace {
            get {
                return ResourceManager.GetString("JSON_ExpectedOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON primitive: {0}..
        /// </summary>
        internal static string JSON_IllegalPrimitive {
            get {
                return ResourceManager.GetString("JSON_IllegalPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array passed in, &apos;]&apos; expected..
        /// </summary>
        internal static string JSON_InvalidArrayEnd {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array passed in, &apos;,&apos; expected..
        /// </summary>
        internal static string JSON_InvalidArrayExpectComma {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayExpectComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array passed in, extra trailing &apos;,&apos;..
        /// </summary>
        internal static string JSON_InvalidArrayExtraComma {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayExtraComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array passed in, &apos;[&apos; expected..
        /// </summary>
        internal static string JSON_InvalidArrayStart {
            get {
                return ResourceManager.GetString("JSON_InvalidArrayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums based on System.Int64 or System.UInt64 are not JSON-serializable because JavaScript does not support the necessary precision..
        /// </summary>
        internal static string JSON_InvalidEnumType {
            get {
                return ResourceManager.GetString("JSON_InvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a positive integer..
        /// </summary>
        internal static string JSON_InvalidMaxJsonLength {
            get {
                return ResourceManager.GetString("JSON_InvalidMaxJsonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object passed in, member name expected..
        /// </summary>
        internal static string JSON_InvalidMemberName {
            get {
                return ResourceManager.GetString("JSON_InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object passed in, &apos;:&apos; or &apos;}&apos; expected..
        /// </summary>
        internal static string JSON_InvalidObject {
            get {
                return ResourceManager.GetString("JSON_InvalidObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecursionLimit must be a positive integer..
        /// </summary>
        internal static string JSON_InvalidRecursionLimit {
            get {
                return ResourceManager.GetString("JSON_InvalidRecursionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property..
        /// </summary>
        internal static string JSON_MaxJsonLengthExceeded {
            get {
                return ResourceManager.GetString("JSON_MaxJsonLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameterless constructor defined for type of &apos;{0}&apos;..
        /// </summary>
        internal static string JSON_NoConstructor {
            get {
                return ResourceManager.GetString("JSON_NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string passed in, &apos;\&quot;&apos; expected..
        /// </summary>
        internal static string JSON_StringNotQuoted {
            get {
                return ResourceManager.GetString("JSON_StringNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string passed in..
        /// </summary>
        internal static string JSON_UnterminatedString {
            get {
                return ResourceManager.GetString("JSON_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to a value type..
        /// </summary>
        internal static string JSON_ValueTypeCannotBeNull {
            get {
                return ResourceManager.GetString("JSON_ValueTypeCannotBeNull", resourceCulture);
            }
        }
    }
}
