CREATE TABLE [dbo].[EXP_TO_SCOPES] (
    [EXP_ID]   NVARCHAR (36) NOT NULL,
    [SCOPE_ID] NVARCHAR (36) NOT NULL,
    CONSTRAINT [PK_EXP_TO_SCOPES] PRIMARY KEY CLUSTERED ([EXP_ID] ASC, [SCOPE_ID] ASC)
);


GO
CREATE TRIGGER [TRIG_EXP_TO_SCOPES_DELETE] ON [dbo].[EXP_TO_SCOPES] 
FOR DELETE 
AS
BEGIN
	INSERT INTO EXP_TO_SCOPES_DELETE SELECT * FROM deleted
END
