CREATE TABLE [dbo].[EXP_TO_SCOPES_DELETE] (
    [EXP_ID]   NVARCHAR (36) NOT NULL,
    [SCOPE_ID] NVARCHAR (36) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_EXP_TO_SCOPES_DELETE]
    ON [dbo].[EXP_TO_SCOPES_DELETE]([EXP_ID] ASC, [SCOPE_ID] ASC) WITH (FILLFACTOR = 50, PAD_INDEX = ON);

