CREATE TABLE [dbo].[EXPRESSIONS_DELETE] (
    [ID]          NVARCHAR (36)  NOT NULL,
    [ROLE_ID]     NVARCHAR (36)  NOT NULL,
    [NAME]        NVARCHAR (32)  NOT NULL,
    [EXPRESSION]  NVARCHAR (512) NOT NULL,
    [DESCRIPTION] NVARCHAR (350) NOT NULL,
    [SORT_ID]     INT            NOT NULL,
    [INHERITED]   NCHAR (1)      NULL,
    [CLASSIFY]    INT            NULL,
    [MODIFY_TIME] DATETIME       NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_EXPRESSIONS_DELETE]
    ON [dbo].[EXPRESSIONS_DELETE]([ROLE_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 50, PAD_INDEX = ON);

