CREATE TABLE [dbo].[EXPRESSIONS] (
    [ID]          NVARCHAR (36)  NOT NULL,
    [ROLE_ID]     NVARCHAR (36)  NOT NULL,
    [NAME]        NVARCHAR (32)  NOT NULL,
    [EXPRESSION]  NVARCHAR (512) NOT NULL,
    [DESCRIPTION] NVARCHAR (350) NOT NULL,
    [SORT_ID]     INT            NOT NULL,
    [INHERITED]   NCHAR (1)      CONSTRAINT [DF_EXPRESSION_INHERITED] DEFAULT (N'n') NULL,
    [CLASSIFY]    INT            NULL,
    [MODIFY_TIME] DATETIME       CONSTRAINT [DF_EXPRESSION_MODIFY_TIME] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_EXPRESSION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_EXPRESSION_ROLE_ID]
    ON [dbo].[EXPRESSIONS]([ROLE_ID] ASC);


GO
CREATE TRIGGER [TRIG_EXPRESSIONS_DELETE] ON dbo.EXPRESSIONS 
FOR DELETE 
AS
BEGIN
	DELETE EXP_TO_SCOPES FROM deleted WHERE EXP_ID = deleted.ID
	INSERT INTO EXPRESSIONS_DELETE SELECT * FROM deleted
END
