CREATE TABLE [dbo].[FUNCTIONS] (
    [ID]          NVARCHAR (36)  NOT NULL,
    [APP_ID]      NVARCHAR (36)  NOT NULL,
    [NAME]        NVARCHAR (32)  NOT NULL,
    [CODE_NAME]   NVARCHAR (32)  NOT NULL,
    [DESCRIPTION] NVARCHAR (128) NULL,
    [SORT_ID]     INT            NOT NULL,
    [INHERITED]   NCHAR (1)      CONSTRAINT [DF_FUNCTIONS_INHERITED] DEFAULT (N'n') NULL,
    [CLASSIFY]    NCHAR (1)      CONSTRAINT [DF_FUNCTIONS_CLASSIFY] DEFAULT (N'n') NULL,
    [MODIFY_TIME] DATETIME       CONSTRAINT [DF_FUNCTION_MODIFY_TIME] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_FUNCTION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CODE_NAME]
    ON [dbo].[FUNCTIONS]([APP_ID] ASC, [CODE_NAME] ASC);


GO
CREATE TRIGGER [TRIG_FUNCION_DELETE] ON [dbo].[FUNCTIONS] 
FOR DELETE 
AS
BEGIN
	DELETE ROLE_TO_FUNCTIONS FROM deleted WHERE FUNC_ID = deleted.ID
	DELETE FUNC_SET_TO_FUNCS FROM deleted WHERE FUNC_ID = deleted.ID
	INSERT INTO FUNCTIONS_DELETE SELECT * FROM deleted
END
