CREATE TABLE [dbo].[FUNC_SET_TO_FUNCS] (
    [FUNC_SET_ID] NVARCHAR (36) NOT NULL,
    [FUNC_ID]     NVARCHAR (36) NOT NULL,
    [SORT_ID]     INT           CONSTRAINT [DF_FUNC_SET_TO_FUNCS_SORT_ID] DEFAULT (0) NOT NULL,
    CONSTRAINT [PK_FUNC_SET_TO_FUNCS] PRIMARY KEY CLUSTERED ([FUNC_SET_ID] ASC, [FUNC_ID] ASC)
);


GO
CREATE TRIGGER [TRIG_FUNC_SET_TO_FUNC_DELETE] ON [dbo].[FUNC_SET_TO_FUNCS] 
FOR DELETE 
AS
BEGIN
	UPDATE FUNCTION_SETS SET CHILDREN_COUNT = CHILDREN_COUNT - (SELECT COUNT(*) FROM deleted WHERE FUNC_SET_ID = FUNCTION_SETS.ID)
	FROM deleted WHERE ID = deleted.FUNC_SET_ID
	INSERT INTO FUNC_SET_TO_FUNCS_DELETE SELECT* FROM deleted
END

GO
CREATE TRIGGER [TRIG_FUNC_SET_TO_FUNC_INSERT] ON [dbo].[FUNC_SET_TO_FUNCS] 
FOR INSERT NOT FOR REPLICATION 
AS
BEGIN
	UPDATE FUNCTION_SETS SET CHILDREN_COUNT = CHILDREN_COUNT + (SELECT COUNT(*) FROM inserted WHERE FUNC_SET_ID = FUNCTION_SETS.ID)
	FROM inserted  WHERE ID = inserted.FUNC_SET_ID;
END
