CREATE TABLE [dbo].[ROLE_PROPERTIES_ROWS] (
    [ROLE_ID]       NVARCHAR (36) NOT NULL,
    [ROW_NUMBER]    INT           NOT NULL,
    [OPERATOR_TYPE] INT           CONSTRAINT [DF_ROLE_PROPERTIES_ROWS_OPERATOR_TYPE] DEFAULT ((2)) NULL,
    [OPERATOR]      NVARCHAR (64) NULL,
    CONSTRAINT [PK_ROLE_PROPERTIES_ROWS] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [ROW_NUMBER] ASC)
);

