CREATE TABLE [dbo].[ROLE_TO_FUNCTIONS] (
    [ROLE_ID]   NVARCHAR (36) NOT NULL,
    [FUNC_ID]   NVARCHAR (36) NOT NULL,
    [INHERITED] NCHAR (1)     CONSTRAINT [DF_ROLE_TO_FUNCTION_INHERITED] DEFAULT (N'n') NULL,
    CONSTRAINT [PK_ROLE_TO_FUNCTIONS] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [FUNC_ID] ASC)
);


GO
CREATE TRIGGER [TRIG_ROLE_TO_FUNCTIONS_DELETE] ON [dbo].[ROLE_TO_FUNCTIONS] 
FOR DELETE 
AS
BEGIN
	INSERT INTO ROLE_TO_FUNCTIONS_DELETE SELECT * FROM deleted
END
