CREATE TABLE [dbo].[ROLE_PROPERTIES_DEFINITIONS] (
    [ROLE_ID]     NVARCHAR (36)  NOT NULL,
    [NAME]        NVARCHAR (64)  NOT NULL,
    [SORT_ORDER]  INT            CONSTRAINT [DF_ROLE_PROPERTIES_DEFINITIONS_SORT_ORDER] DEFAULT ((0)) NULL,
    [DESCRIPTION] NVARCHAR (256) NULL,
    [DATA_TYPE]   INT            CONSTRAINT [DF_ROLE_PROPERTIES_DEFINITIONS_DATA_TYPE] DEFAULT ((18)) NULL,
    CONSTRAINT [PK_ROLE_PROPERTIES_DEFINITIONS] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [NAME] ASC)
);

