CREATE TABLE [dbo].[ROLES] (
    [ID]             NVARCHAR (36)  NOT NULL,
    [APP_ID]         NVARCHAR (36)  NOT NULL,
    [NAME]           NVARCHAR (32)  NOT NULL,
    [CODE_NAME]      NVARCHAR (32)  NOT NULL,
    [DESCRIPTION]    NVARCHAR (128) NULL,
    [CLASSIFY]       NCHAR (1)      CONSTRAINT [DF_ROLES_CLASSIFY] DEFAULT (N'n') NOT NULL,
    [SORT_ID]        INT            NOT NULL,
    [INHERITED]      NCHAR (1)      CONSTRAINT [DF_ROLES_INHERITED] DEFAULT (N'n') NULL,
    [ALLOW_DELEGATE] NCHAR (1)      CONSTRAINT [DF_ROLES_ALLOW_DELEGATE] DEFAULT (N'n') NULL,
    [MODIFY_TIME]    DATETIME       CONSTRAINT [DF_ROLE_MODIFY_TIME] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ROLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_APP_ID]
    ON [dbo].[ROLES]([APP_ID] ASC) WITH (FILLFACTOR = 50, PAD_INDEX = ON);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CODE_NAME]
    ON [dbo].[ROLES]([APP_ID] ASC, [CODE_NAME] ASC);


GO
CREATE TRIGGER [TRIG_ROLE_DELETE] ON dbo.ROLES 
FOR DELETE 
AS
BEGIN
	DELETE ROLE_TO_FUNCTIONS FROM deleted WHERE ROLE_ID = deleted.ID
	DELETE EXPRESSIONS FROM deleted WHERE ROLE_ID = deleted.ID
	DELETE DELEGATIONS FROM deleted WHERE ROLE_ID = deleted.ID
	INSERT INTO ROLES_DELETE SELECT * FROM deleted
END
