CREATE TABLE [dbo].[ROLE_PROPERTIES_CELLS] (
    [ROLE_ID]           NVARCHAR (36)  NOT NULL,
    [PROPERTIES_ROW_ID] INT            NOT NULL,
    [PROPERTY_NAME]     NVARCHAR (64)  NOT NULL,
    [STRING_VALUE]      NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_ROLE_PROPERTIES_CELLS] PRIMARY KEY CLUSTERED ([ROLE_ID] ASC, [PROPERTIES_ROW_ID] ASC, [PROPERTY_NAME] ASC)
);

