CREATE TABLE [dbo].[ROLE_TO_FUNCTIONS_DELETE] (
    [ROLE_ID]   NVARCHAR (36) NOT NULL,
    [FUNC_ID]   NVARCHAR (36) NOT NULL,
    [INHERITED] NCHAR (1)     NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ROLE_TO_FUNCTIONS_DELETE]
    ON [dbo].[ROLE_TO_FUNCTIONS_DELETE]([ROLE_ID] ASC, [FUNC_ID] ASC) WITH (FILLFACTOR = 50, PAD_INDEX = ON);

