CREATE TABLE [dbo].[SCOPES] (
    [ID]          NVARCHAR (36)  NOT NULL,
    [APP_ID]      NVARCHAR (36)  NOT NULL,
    [NAME]        NVARCHAR (32)  NOT NULL,
    [CODE_NAME]   NVARCHAR (32)  NOT NULL,
    [EXPRESSION]  NVARCHAR (500) NOT NULL,
    [DESCRIPTION] NVARCHAR (350) NOT NULL,
    [CLASSIFY]    NCHAR (1)      CONSTRAINT [DF_SCOPES_CLASSIFY] DEFAULT (N'y') NULL,
    [SORT_ID]     INT            NOT NULL,
    [INHERITED]   NCHAR (1)      CONSTRAINT [DF_SCOPE_INHERITED] DEFAULT (N'n') NULL,
    [MODIFY_TIME] DATETIME       CONSTRAINT [DF_SCOPE_MODIFY_TIME] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_SCOPE] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_APP_ID_CODE_NAME]
    ON [dbo].[SCOPES]([APP_ID] ASC, [CODE_NAME] ASC) WITH (FILLFACTOR = 50, PAD_INDEX = ON);


GO
CREATE TRIGGER [TRIG_SCOPE_DELETE] ON dbo.SCOPES 
FOR DELETE 
AS
BEGIN
	DELETE EXP_TO_SCOPES FROM deleted WHERE SCOPE_ID = deleted.ID
	INSERT INTO SCOPES_DELETE SELECT * FROM deleted
END
