CREATE TABLE [dbo].[SCOPES_DELETE] (
    [ID]          NVARCHAR (36)  NOT NULL,
    [APP_ID]      NVARCHAR (36)  NOT NULL,
    [NAME]        NVARCHAR (32)  NOT NULL,
    [CODE_NAME]   NVARCHAR (32)  NOT NULL,
    [EXPRESSION]  NVARCHAR (500) NOT NULL,
    [DESCRIPTION] NVARCHAR (350) NOT NULL,
    [CLASSIFY]    NCHAR (1)      NULL,
    [SORT_ID]     INT            NOT NULL,
    [INHERITED]   NCHAR (1)      NULL,
    [MODIFY_TIME] DATETIME       NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_SCOPES_DELETE]
    ON [dbo].[SCOPES_DELETE]([APP_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 50, PAD_INDEX = ON);

