CREATE TABLE [dbo].[WEB_READ_LOG] (
    [GUID]            UNIQUEIDENTIFIER NOT NULL,
    [WEB_METHOD_NAME] NVARCHAR (128)   NOT NULL,
    [INPUT_STREAM]    NTEXT            NULL,
    [OUTPUT_STREAM]   NTEXT            NULL,
    [START_DATE]      DATETIME         NOT NULL,
    [END_DATE]        DATETIME         NOT NULL,
    [HOST_IP]         NVARCHAR (16)    NOT NULL,
    PRIMARY KEY NONCLUSTERED ([GUID] ASC)
);


GO
CREATE CLUSTERED INDEX [IX_WEB_READ_LOG_START_DATE]
    ON [dbo].[WEB_READ_LOG]([START_DATE] ASC);

