//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Web.Responsive.WebControls.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Web.Responsive.WebControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 value must be of type MCS.Web.WebControls.ButtonItemExtender 的本地化字符串。
        /// </summary>
        internal static string ButtonItemExtenderValidateError {
            get {
                return ResourceManager.GetString("ButtonItemExtenderValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能转换相对部门类型为{0}的资源 的本地化字符串。
        /// </summary>
        internal static string CanNotConvertResourceByRelativeDeptType {
            get {
                return ResourceManager.GetString("CanNotConvertResourceByRelativeDeptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能获取类型为{0}的资源定义的JSON转换器 的本地化字符串。
        /// </summary>
        internal static string CanNotGetConverterFromResType {
            get {
                return ResourceManager.GetString("CanNotGetConverterFromResType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能获取资源类型为{0}的资源数据 的本地化字符串。
        /// </summary>
        internal static string CanNotGetResourceData {
            get {
                return ResourceManager.GetString("CanNotGetResourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件被禁用 的本地化字符串。
        /// </summary>
        internal static string ControlDisabled {
            get {
                return ResourceManager.GetString("ControlDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件{0}不存在 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有提供文件路径({0}) 的本地化字符串。
        /// </summary>
        internal static string FilePathNullOrEmpty {
            get {
                return ResourceManager.GetString("FilePathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}路径不合法 的本地化字符串。
        /// </summary>
        internal static string IllegalPath {
            get {
                return ResourceManager.GetString("IllegalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}路径不合法 的本地化字符串。
        /// </summary>
        internal static string IllegalPath1 {
            get {
                return ResourceManager.GetString("IllegalPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源已被{0}加锁，并已过期，验证失败 的本地化字符串。
        /// </summary>
        internal static string LockByAnotherAndExpire {
            get {
                return ResourceManager.GetString("LockByAnotherAndExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源已被{0}加锁 的本地化字符串。
        /// </summary>
        internal static string LockedByAnother {
            get {
                return ResourceManager.GetString("LockedByAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁未过期 的本地化字符串。
        /// </summary>
        internal static string LockedByRight {
            get {
                return ResourceManager.GetString("LockedByRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁已过期，请重新加锁 的本地化字符串。
        /// </summary>
        internal static string LockedByRightAndExpire {
            get {
                return ResourceManager.GetString("LockedByRightAndExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁对象无效 的本地化字符串。
        /// </summary>
        internal static string LockEntityInvalid {
            get {
                return ResourceManager.GetString("LockEntityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaterialControl在{0}使用方式下，{1} 的本地化字符串。
        /// </summary>
        internal static string MaterialControlCheckMode {
            get {
                return ResourceManager.GetString("MaterialControlCheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原资源锁已被破坏 的本地化字符串。
        /// </summary>
        internal static string NotLocked {
            get {
                return ResourceManager.GetString("NotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象{0}为空 的本地化字符串。
        /// </summary>
        internal static string ObjectIsNull {
            get {
                return ResourceManager.GetString("ObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门ID为空 的本地化字符串。
        /// </summary>
        internal static string SelectedDepartmentIDError {
            get {
                return ResourceManager.GetString("SelectedDepartmentIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源已被{0}加锁，并已过期，将覆盖原锁 的本地化字符串。
        /// </summary>
        internal static string TryLockByAnotherAndExpire {
            get {
                return ResourceManager.GetString("TryLockByAnotherAndExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源已被{0}加锁，并没过期，加锁失败 的本地化字符串。
        /// </summary>
        internal static string TryLockedByAnother {
            get {
                return ResourceManager.GetString("TryLockedByAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源已被该用户加锁，并没过期，将覆盖原锁 的本地化字符串。
        /// </summary>
        internal static string TryLockedByRight {
            get {
                return ResourceManager.GetString("TryLockedByRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源已被该用户加锁，并已过期，将覆盖原锁 的本地化字符串。
        /// </summary>
        internal static string TryLockedByRightAndExpire {
            get {
                return ResourceManager.GetString("TryLockedByRightAndExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该资源没有被加锁，添加新锁 的本地化字符串。
        /// </summary>
        internal static string TryNotLocked {
            get {
                return ResourceManager.GetString("TryNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不符合{0}的类型。 的本地化字符串。
        /// </summary>
        internal static string TypeNotMatch {
            get {
                return ResourceManager.GetString("TypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载模板文件。 的本地化字符串。
        /// </summary>
        internal static string UnableToLoadTemplate {
            get {
                return ResourceManager.GetString("UnableToLoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择下一步的流转人员 的本地化字符串。
        /// </summary>
        internal static string WfMustSelectNextOperator {
            get {
                return ResourceManager.GetString("WfMustSelectNextOperator", resourceCulture);
            }
        }
    }
}
