CREATE VIEW [WF].[UNION_APP_AND_ALIAS_PROGRAM_VIEW]
AS
SELECT A.CODE_NAME AS APPLICATION_CODE_NAME, P.CODE_NAME
FROM WF.APPLICATIONS A INNER JOIN WF.PROGRAMS P ON A.CODE_NAME = P.APPLICATION_CODE_NAME
UNION
SELECT APP_ALIAS_CODE_NAME APPLICATION_CODE_NAME, P.CODE_NAME
FROM WF.APPLICATIONS A INNER JOIN WF.APPLICATIONS_ALIAS ALIAS ON A.CODE_NAME = ALIAS.APP_CODE_NAME INNER JOIN WF.PROGRAMS P ON A.CODE_NAME = P.APPLICATION_CODE_NAME