CREATE VIEW [WF].[UNION_APP_AUTH_WITH_ALIAS]
AS
SELECT APA.APPLICATION_NAME, APA.PROGRAM_NAME, APA.AUTH_TYPE, APA.ROLE_ID, APA.ROLE_DESCRIPTION, APA.CREATE_TIME
FROM WF.APP_PROGRAM_AUTH APA
UNION
SELECT AA.APP_ALIAS_CODE_NAME, APA.PROGRAM_NAME, APA.AUTH_TYPE, APA.ROLE_ID, APA.ROLE_DESCRIPTION, APA.CREATE_TIME
FROM WF.APP_PROGRAM_AUTH APA INNER JOIN WF.APPLICATIONS_ALIAS AA ON APA.APPLICATION_NAME = AA.APP_CODE_NAME