//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Library.OGUPermission.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Library.OGUPermission.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能找到对象&quot;{0}&quot;.
        /// </summary>
        internal static string CanNotFindObject {
            get {
                return ResourceManager.GetString("CanNotFindObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能找到根机构，路径为&quot;{0}&quot;.
        /// </summary>
        internal static string CanNotFindRootOU {
            get {
                return ResourceManager.GetString("CanNotFindRootOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前不支持这种类型的对象的构造{0}.
        /// </summary>
        internal static string InvalidObjectTypeCreation {
            get {
                return ResourceManager.GetString("InvalidObjectTypeCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只有查询用户时，才能使用LogOnName作为查询条件.
        /// </summary>
        internal static string OnlyUserCanUserLogOnNameQuery {
            get {
                return ResourceManager.GetString("OnlyUserCanUserLogOnNameQuery", resourceCulture);
            }
        }
    }
}
