//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Library.Accredit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Library.Accredit.Properties.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccreditAdmin.
        /// </summary>
        internal static string AccreditConnAlias {
            get {
                return ResourceManager.GetString("AccreditConnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccreditAdmin.
        /// </summary>
        internal static string AppConnAlias {
            get {
                return ResourceManager.GetString("AppConnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005531da-bbc7-4edb-9db9-f2269108d9fb.tmp.
        /// </summary>
        internal static string CacheDependenceFile {
            get {
                return ResourceManager.GetString("CacheDependenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCS.Library.Accredit.WebBase.ErrorTemplate.htm.
        /// </summary>
        internal static string ErrorTemplate {
            get {
                return ResourceManager.GetString("ErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG.
        /// </summary>
        internal static string LogConnAlias {
            get {
                return ResourceManager.GetString("LogConnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000.
        /// </summary>
        internal static string OriginalSortDefault {
            get {
                return ResourceManager.GetString("OriginalSortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccreditAdmin.
        /// </summary>
        internal static string SoapLogConnAlias {
            get {
                return ResourceManager.GetString("SoapLogConnAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUPS.
        /// </summary>
        internal static string Table_Group {
            get {
                return ResourceManager.GetString("Table_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP_USERS.
        /// </summary>
        internal static string Table_GroupUser {
            get {
                return ResourceManager.GetString("Table_GroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZATIONS.
        /// </summary>
        internal static string Table_Org {
            get {
                return ResourceManager.GetString("Table_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU_USERS.
        /// </summary>
        internal static string Table_OuUser {
            get {
                return ResourceManager.GetString("Table_OuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWD_ARITHMETIC.
        /// </summary>
        internal static string Table_Pwd {
            get {
                return ResourceManager.GetString("Table_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANK_DEFINE.
        /// </summary>
        internal static string Table_RankDefine {
            get {
                return ResourceManager.GetString("Table_RankDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECRETARIES.
        /// </summary>
        internal static string Table_Secretary {
            get {
                return ResourceManager.GetString("Table_Secretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS.
        /// </summary>
        internal static string Table_User {
            get {
                return ResourceManager.GetString("Table_User", resourceCulture);
            }
        }
    }
}
