CREATE TABLE [WF].[POST] (
    [POST_ID]      NVARCHAR (36) NOT NULL,
    [POST_NAME]    NVARCHAR (64) NOT NULL,
    [CATEGORY]     NVARCHAR (64) NULL,
    [CREATE_TIME]  DATETIME      NOT NULL,
    [CREATOR_ID]   NVARCHAR (36) NOT NULL,
    [CREATOR_NAME] NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_WF_POST] PRIMARY KEY CLUSTERED ([POST_ID] ASC)
);

